# Site settings
title: "Levi Baber"
description: "Levi Baber: Technical Manager"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Levi Baber"
resume_title:                   "Research IT Director"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "baberlevi@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "address • phone • email"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced technical leader with interests in Linux, open source, large scale computing, and science.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_publications:    true
resume_section_interests:       false
resume_section_instruction:     true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:           "https://github.com/baberlevi"
  #resume_twitter_url:           "http://twitter.com/baberlevi"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:         "https://www.linkedin.com/in/baberlevi"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:          "http://baberlevi.github.io/resume"
  #resume_medium_url:            "insert medium URL here"
  resume_googlescholar_url:    "https://scholar.google.com/citations?hl=en&user=B_Zd9jkAAAAJ"
  resume_orcid_url:            "https://orcid.org/0000-0002-0691-2962"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
